add_subdirectory(sysconfig)
add_subdirectory(template)
add_subdirectory(log)
add_subdirectory(ble)
add_subdirectory(crash)
add_subdirectory(ota)
add_subdirectory(osal)
add_subdirectory(utkernel-cpp)
add_subdirectory(signal)
add_subdirectory(shell)
add_subdirectory(flash_fs)
add_subdirectory(beacon)
add_subdirectory(drivers)
